<?php


/**
 * This class defines the structure of the 'file_trunk' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Thu Jun 10 06:47:21 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfFileTrunkPlugin.lib.model.map
 */
class FileTrunkTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfFileTrunkPlugin.lib.model.map.FileTrunkTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('file_trunk');
		$this->setPhpName('FileTrunk');
		$this->setClassname('FileTrunk');
		$this->setPackage('plugins.sfFileTrunkPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('ORIGINAL_NAME', 'OriginalName', 'VARCHAR', true, 255, null);
		$this->addColumn('ACTUAL_NAME', 'ActualName', 'VARCHAR', true, 255, null);
		$this->addColumn('MIME_TYPE', 'MimeType', 'VARCHAR', true, 255, null);
		$this->addColumn('SIZE', 'Size', 'INTEGER', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('MmEvent', 'MmEvent', RelationMap::ONE_TO_MANY, array('id' => 'file_trunk_id', ), 'RESTRICT', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'false', 'filter' => 'false', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // FileTrunkTableMap
