<?php

require 'plugins/sfFileTrunkPlugin/lib/model/om/BaseFileTrunkPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'file_trunk' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sun Jan  3 06:35:37 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfFileTrunkPlugin.lib.model
 */
class FileTrunkPeer extends BaseFileTrunkPeer {

} // FileTrunkPeer
